### ISSUE TITLE
No way to add background.

### ISSUE THREAD

**Issue by oscie57** [Sudomemo/Sudotheme#1]
On some Sudomemo themes, there are backgrounds, like in the Hatena theme there is a grid-paper background for the bottom screen, whereas there isn't an option for this on these.

**Comment by jaames** [comment]
I don't work on Sudomemo anymore, but for what it's worth this stuff was created before the bottom screen backgrounds were discovered. They're just tiled squares though (8x8 pixels or so, iirc?) so shouldn't be too hard to just make yourself.

**Comment by Oscie57** [comment]
Ah alright, thanks

**Comment by oscie57** [comment]
i dont need this open anymore, and my question was answered so
